version: '3.7'
services:
  backend:
    build:
      context: .
    container_name: petfinder-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - petfinder-network

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - petfinder-network

networks:
  petfinder-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
