GET http://localhost:5000/api/v1/users
###
GET http://localhost:27017/api/v1/users/1
###
POST http://localhost:5000/api/v1/users/
Content-Type: application/json

{
    "username": "John Doe",
    "email": "john.doe@example.com",
    "password": "password",
}
###
curl -X POST http://localhost:27017/api/v1/users/ -H 'Content-Type: application/json' -d '{"username": "John Doe","email": "
